"""chat's images

Revision ID: 41d3e7df1ee4
Revises: 4e3222003f80
Create Date: 2021-05-02 10:33:49.352498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d3e7df1ee4'
down_revision = '4e3222003f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('image', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'image')
    # ### end Alembic commands ###
