"""new fields in chat model

Revision ID: 72c4702fa9d9
Revises: b6da7a9712bc
Create Date: 2021-02-13 13:39:13.070009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c4702fa9d9'
down_revision = 'b6da7a9712bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chats',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('author_books')
    op.add_column('chat', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_chat_name'), 'chat', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_name'), table_name='chat')
    op.drop_column('chat', 'name')
    op.create_table('author_books',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('chat_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_chats')
    # ### end Alembic commands ###
