"""new field in post model

Revision ID: ad59ddbc3550
Revises: 72c4702fa9d9
Create Date: 2021-02-13 14:47:53.827604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad59ddbc3550'
down_revision = '72c4702fa9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'chat_id')
    # ### end Alembic commands ###
